# Generated by Django 5.1.2 on 2025-01-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
