# Generated by Django 5.1.2 on 2024-11-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron', models.CharField(max_length=100)),
                ('funct', models.CharField(max_length=255)),
                ('args', models.CharField(max_length=255, null=True)),
                ('kwargs', models.CharField(max_length=255, null=True)),
                ('repeat', models.IntegerField(null=True)),
                ('result_ttl', models.IntegerField(null=True)),
                ('ttl', models.IntegerField(null=True)),
                ('queue', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('PULL', 'Pull'), ('PUSH', 'Push'), ('VALIDATE', 'Validate')], max_length=10)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
