name: DRF Deploy CICD

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: self-hosted
    env:
      DJANGO_SECRET_KEY: 'nshf93fb8vgds73gfi'
      REDIS_HOST: 'localhost'
      REDIS_PORT: 6379

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: python manage.py test

  deploy:
    needs: build
    runs-on: self-hosted

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Pull from Github repo
        run: |
            cd /var/www/ci_cd-drf
            sudo git pull origin master
            source venv/bin/activate
            python manage.py migrate
            deactivate

      - name: Deploy via Supervisor
        run: |
          echo "Deploying commit: $GITHUB_SHA"
          sudo supervisorctl restart all              
